extends Node

@warning_ignore("unused_signal")
signal tower_placed()
@warning_ignore("unused_signal")
signal tower_destroyed()
@warning_ignore("unused_signal")
signal tower_selected(tower: Tower)
@warning_ignore("unused_signal")
signal tower_deselected()
@warning_ignore("unused_signal")
signal tower_sold(tower: Tower, refund: int)
@warning_ignore("unused_signal")
signal navmesh_updated()
@warning_ignore("unused_signal")
signal exits_updated()
@warning_ignore("unused_signal")
signal spawners_updated()


@warning_ignore("unused_signal")
signal placement_mode_changed(is_active: bool)

@warning_ignore("unused_signal")
signal enemy_spawned(enemy: Enemy)
@warning_ignore("unused_signal")
signal enemy_died(enemy: Enemy)
@warning_ignore("unused_signal")
signal enemy_exit(enemy: Enemy)

@warning_ignore("unused_signal")
signal lives_changed(lives: int)
@warning_ignore("unused_signal")
signal energy_changed(energy: int)

@warning_ignore("unused_signal")
signal wave_changed(wave: int)
@warning_ignore("unused_signal")
signal wave_started()
@warning_ignore("unused_signal")
signal wave_completed()
@warning_ignore("unused_signal")
signal stage_loaded()
@warning_ignore("unused_signal")
signal stage_completed(stage_id: String)
@warning_ignore("unused_signal")
signal stage_failed()

@warning_ignore("unused_signal")
signal score_changed(score: int)
@warning_ignore("unused_signal")
signal stage_time_changed(formatted_time: String)

@warning_ignore("unused_signal")
signal credits_changed(credits: int)
@warning_ignore("unused_signal")
signal tower_unlocked(tower_id: String)
@warning_ignore("unused_signal")
signal tower_upgraded(tower_id: String, new_level: int)
@warning_ignore("unused_signal")
signal specialization_unlocked(tower_id: String, choice_id: String)
@warning_ignore("unused_signal")
signal tower_choice_changed(tower_id: String, choice_id: String)
@warning_ignore("unused_signal")
signal stage_unlocked(stage_id: String)
@warning_ignore("unused_signal")
signal rewarded_ad_reward_earned(amount: int)
